### ISSUE TITLE
boost dependency

### ISSUE THREAD

**Issue by rchikhi** [Kingsford-Group/kbf#1]
Hi,

Good work on kbf :)

I wanted to give it a try in a small project, but not really keen on having Boost as a dependency. I see that you use it only for a fibonacci heap? Libbf has removed that dependency recently.

Rayan

**Comment by lynxoid** [comment]
Rayan,

Thanks for your interest. We use fibonacci heap for the hitting set algorithm when sparsifying the set of kmers that we put in the BF. You should still be able to use the BestMatch sparsification approach w/o the heap. Additionally, you can try swapping out the fib. heap for standard C++ STL priority_queue implementation (although that would make hitting set slower). Hope this helps!

**Comment by lynxoid** [comment]
And btw I agree w/ you that not having boost as a dependency would make life so much easier :)

**Comment by rchikhi** [comment]
Thanks for those indications!
